name: Hello GitHub Actions
on:
  push:
    branches: [main]

jobs:
  hello:
    name: Hi!
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
